---
- hosts: all
  remote_user: heat-admin
  become: yes
  tasks:
    - name: Install SystemTap
      shell: |
        yum install -y systemtap kernel-devel-`uname -r`
        debuginfo-install -y kernel-`uname -r`
        stap -v -e 'probe vfs.read {printf("read performed\n"); exit()}'
    - name: Clone capabilities tracker
      git:
       repo: https://github.com/xek/capabilities_tracker
       dest: capabilities_tracker
    - name: Start SystemTap
      shell: >
        cd capabilities_tracker &&
        nohup ./systap_test.sh ../capabilities.log
        </dev/null >/dev/null 2>&1 &
    - name: Wait
      pause:
        seconds: 120
    - name: Restart container
      command: docker restart logrotate_crond
    - name: Wait
      pause:
        seconds: 140
    - name: Stop SystemTup
      command: pkill stap
    - name: Wait
      pause:
        seconds: 15
    - name: Get logs
      fetch:
        src: capabilities.log
        dest: capabilities-{{ inventory_hostname }}.log
        flat: yes
