apiVersion: v1
kind: Namespace
metadata:
  name: capabilities-tracker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: capabilities-tracker
  namespace: capabilities-tracker
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: capabilities-tracker
subjects:
- kind: ServiceAccount
  name: capabilities-tracker
  namespace: capabilities-tracker
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: capabilities-tracker
  namespace: capabilities-tracker
  labels:
    app: capabilities-tracker
spec:
  selector:
    matchLabels:
      app: capabilities-tracker
  template:
    metadata:
      labels:
        app: capabilities-tracker
      annotations:
        capabilities-tracker.clustership.io/option-runc-hooks: "crio"
    spec:
      serviceAccount: capabilities-tracker
      hostPID: true
      hostNetwork: true
      containers:
      - name: capabilities-tracker
        image: quay.io/xymox/capable:fedora-0.6
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "sleep infinity"]
        lifecycle:
          preStop:
            exec:
              command:
                - "/cleanup.sh"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CAPS_POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: CAPS_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CAPS_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CAPS_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        securityContext:
          privileged: true
        volumeMounts:
        - name: host
          mountPath: /host
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        - name: debugfs
          mountPath: /sys/kernel/debug
        - name: cgroup
          mountPath: /sys/fs/cgroup
        - name: bpffs
          mountPath: /sys/fs/bpf
        - name: localtime
          mountPath: /etc/localtime
        - name: headers
          mountPath: /usr/src
          readOnly: true
        - name: infos
          mountPath: /infos
          readOnly: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: host
        hostPath:
          path: /
      - name: run
        hostPath:
          path: /run
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: modules
        hostPath:
          path: /lib/modules
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: headers
        hostPath:
          path: /usr/src
      - name: infos
        hostPath:
          path: /var/tmp
